#!/usr/bin/env node
// Generate Base Config Schema script supports OpenClaw repository automation.
import { pathToFileURL } from "node:url";
import { computeBaseConfigSchemaResponse } from "../src/config/schema-base.js";

export function checkBaseConfigSchema(): void {
  computeBaseConfigSchemaResponse({
    generatedAt: "2026-05-05T00:00:00.000Z",
  });
}

<<<<<<< HEAD
export function renderBaseConfigSchemaModule(params?: { generatedAt?: string }): string {
  const payload = computeBaseConfigSchemaResponse({
    generatedAt: params?.generatedAt ?? new Date().toISOString(),
  });
  return formatTypeScriptModule(
    `// Auto-generated by ${GENERATED_BY}. Do not edit directly.

import type { BaseConfigSchemaResponse } from "./schema-base.js";

export const GENERATED_BASE_CONFIG_SCHEMA: BaseConfigSchemaResponse = ${JSON.stringify(payload, null, 2)};
`,
    DEFAULT_OUTPUT_PATH,
  );
}

export function writeBaseConfigSchemaModule(params?: {
  repoRoot?: string;
  outputPath?: string;
  check?: boolean;
}): { changed: boolean; wrote: boolean; outputPath: string } {
  const repoRoot = path.resolve(params?.repoRoot ?? REPO_ROOT);
  const outputPath = path.resolve(repoRoot, params?.outputPath ?? DEFAULT_OUTPUT_PATH);
  const current = readIfExists(outputPath);
  const generatedAt =
    current?.match(/generatedAt:\s*"([^"]+)"/u)?.[1] ??
    current?.match(/"generatedAt":\s*"([^"]+)"/u)?.[1] ??
    new Date().toISOString();
  const next = renderBaseConfigSchemaModule({ generatedAt });
  const changed = current !== next;

  if (params?.check) {
    return { changed, wrote: false, outputPath };
  }

  if (changed) {
    fs.writeFileSync(outputPath, next, "utf8");
  }
  return { changed, wrote: changed, outputPath };
}

=======
>>>>>>> upstream/main
const args = new Set(process.argv.slice(2));
if (args.has("--check") && args.has("--write")) {
  throw new Error("Use either --check or --write, not both.");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  checkBaseConfigSchema();
  if (args.has("--write")) {
    console.log("[base-config-schema] runtime-computed; no generated file to write");
  } else {
    console.log("[base-config-schema] ok");
  }
}
